version: '2'

services:

  freme-broker:
    image: fremeproject/freme-broker
    ports:
     - "4000:8080"
    depends_on:
     - freme-mysql
     - freme-virtuoso
     - freme-solr
    volumes:
     - /opt/freme-data/logs:/logs
    env_file:
     - config.env

    restart: always


  freme-mysql:
    image: "fremeproject/freme-mysql-${FREME_DISTRIBUTION}"
    env_file:
      - config.env
    restart: always

  freme-virtuoso:
    image: tenforce/virtuoso
    env_file:
      - config.env
    environment:
      - SPARQL_UPDATE=true
      - DEFAULT_GRAPH=http://www.example.com/my-graph
    restart: always
    volumes:
      - /opt/freme-data/solr/elinker/virtuoso:/data 

  freme-solr:
    image: fremeproject/freme-solr
    ports:
      - "4001:8890" 
    volumes:
     - /opt/freme-data/solr/elinker/:/opt/solr/server/solr/elinker
    restart: always

