version: '2'
services:

  freme-broker:
    image: fremeproject/freme-broker
    ports:
     - "4000:8080"
    depends_on:
     - freme-mysql
     - freme-virtuoso
     - freme-solr

  freme-mysql:
    image: fremeproject/freme-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "40001:3306"

  freme-virtuoso:
    image: tenforce/virtuoso
    environment:
      - DBA_PASSWORD=dba
      - SPARQL_UPDATE=true
      - DEFAULT_GRAPH=http://www.example.com/my-graph
  
  freme-solr:
    image: fremeproject/freme-solr
