version: '2'
services:

  freme-broker:
    image: fremeproject/freme-broker
    ports:
     - "4000:8080"
    depends_on:
     - freme-mysql
     - freme-virtuoso
     - freme-solr
    volumes:
     - /opt/freme-data/logs:/logs
    environment:
      - ADMIN_PASSWORD=123
    restart: always


  freme-mysql:
    image: fremeproject/freme-mysql-data
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "40001:3306"
    restart: always

  freme-virtuoso:
    image: tenforce/virtuoso
    environment:
      - DBA_PASSWORD=dba
      - SPARQL_UPDATE=true
      - DEFAULT_GRAPH=http://www.example.com/my-graph
    restart: always
  
  freme-solr:
    image: fremeproject/freme-solr
    ports:
      - "4003:8983"
    volumes:
     - /opt/freme-data/solr/elinker/:/opt/solr/server/solr/elinker
    restart: always

