ner:
  build: ./freme-ner
  command: /opt/freme-ner/bin/freme-ner.sh
  ports:
    - "7002:7002"   
  links:
   - db  
   - solr
   - virtuoso
solr:
  build: ./freme-ner-solr
  ports:
    - "8983:8983" 
  links:
   - db    
  volumes:
    - /mnt/data/solr/elinker:/opt/solr/server/solr/elinker
virtuoso:
  image: tenforce/virtuoso
  ports:
    - "8890:8890" 
    - "1111:1111" 
  volumes:
    - /mnt/data/virtuoso:/data
  environment:
    DBA_PASSWORD: freme
    SPARQL_UPDATE: "true"
    DEFAULT_GRAPH: "http://www.freme-project.eu/graph"
db:
  image: mysql
  ports:
    - "3306:3306"  
  environment:
    MYSQL_ROOT_PASSWORD: freme
    MYSQL_USER: freme
    MYSQL_PASSWORD: freme
    MYSQL_DATABASE: freme
